version: '3.5'

services: 
    flask-api:
        container_name: app-app
        restart: always
        build:
            context: ./service/
            dockerfile: Dockerfile
        expose:
            - "5000"
        ports:
            - "5000:5000"
        volumes:
            - ./service:/usr/src/app
        environment: 
            - FLASK_ENV=development
            - FLASK_APP=app.py
            - FLASK_DEBUG=1

    client:
        container_name: react-app
        build:
            context: ./ui
            dockerfile: Dockerfile
        expose:
            - "3000"
        ports:
            - "3000:3000"
        volumes:
            - './ui:/usr/src/app'
        depends_on: 
            - "flask-api" 

